### ISSUE TITLE
Неверное склонение некоторых мужских фамилий

### ISSUE THREAD

**Issue by caffeinum** [petrovich/petrovich-ruby#13]
**Пример**

Быхун Алексей Викторович
...
тво.
Быхуным Алексеем Викторовичем
...

Правильно склонять "Быхуном"

Баг повторяется для всех фамилий на "ун", "он", "ен"

**Comment by jenkek** [comment]
еще пример из этой серии:

Коломиец Иван Петрович
...
род.
Коломица Ивана Петровича
...
Правильно "Коломийца"
