### ISSUE TITLE
Даша склоняенься в родительном падеже как Дашы

### ISSUE THREAD

**Issue by Tolia** [petrovich/petrovich-ruby#39]
![](https://s3.amazonaws.com/f.cl.ly/items/0q0R2p0e0w102J1v1q1M/Screen%20Shot%202015-01-07%20at%2015.47.56.png)

**Comment by tanraya** [comment]
Привет.  В этом интерфейсе нужно вводить ФИО. Например: Иванова Даша Ивановна
В этом случае, все будет склоняться верно.
При использовании гема используйте метод `firstname` для склонения имени.

**Comment by ujifgc** [comment]
Хочу заметить, что `Дажа` в этом интерфейсе склоняется в `Дажи`, однако `Даша` в `Дашы`. Очень странно.

**Comment by tanraya** [comment]
Это не странно, просто в если вы указываете одно слово в этом интерфейсе - оно склоняется по правилам фамилий. Прафила для имён и фамилий - различаются.
Обратите внимание на правую колонку с примером, здесь http://petrovich.rocketscience.it/

**Comment by tanraya** [comment]
Подробнее.

Для склонения `Дажа` используется вот это правило https://github.com/petrovich/petrovich-rules/blob/master/rules.yml#L103

Для склонения `Даша` - вот это https://github.com/petrovich/petrovich-rules/blob/master/rules.yml#L107

Еще раз обращаю внимание на то, что эти правила для склонения фамилий, т.к. при указании одного слова в интерфейсе оно подразумевается как фамилия.

**Comment by ujifgc** [comment]
Фамилия Кваша склоняется в Квашы. Я на это хотел внимание обратить. Жы-Шы пиши с буквой и.

**Comment by tanraya** [comment]
А вот это уже ошибка. Спасибо, запишу ее в issues.

**Comment by ujifgc** [comment]
Извините за любопытство и назойливость, но почему вы посчитали, что Даша в Дашы — не ошибка? Какие-то спецправила русского языка применяются (причём, только для Шы, но не для Жи), когда пользователь не туда что-то ввёл?

**Comment by tanraya** [comment]
> Извините за любопытство и назойливость, но почему вы посчитали, что Даша в Дашы — не ошибка? 

Конечно же, это ошибка. Я сейчас занимаюсь её исправлением :)

**Comment by tanraya** [comment]
Спешу сообщить, что правила пофикшены, а так же выпущеная новая версия `0.2.1`

Обновляйтесь: `bundle update petrovich`
Всем спасибо за участие :+1:

**Comment by Tolia** [comment]
@tanraya спасибо!
