### ISSUE TITLE
Неверное склонение имён "Саша", "Даша" и т.д. в творительном падеже

### ISSUE THREAD

**Issue by EugZol** [petrovich/petrovich-ruby#40]
2.1.1> Petrovich.new(:male).firstname('Маша', :instrumental)
     => "Машой"
    2.1.1> Petrovich.new(:male).firstname('Даша', :instrumental)
     => "Дашой"

Вместо "Машей", "Дашей".

**Comment by tanraya** [comment]
Спасибо, посмотрим где в словаре проблема.

**Comment by EugZol** [comment]
Ой! Я ж пол человека неправильно указал. Извините, всё правильно работает :)

**Comment by tanraya** [comment]
Спасибо. А то я проверил у себя, все правильно было. Подумал, может у вас словарь старый был. А вот оно что оказалось.
