### ISSUE TITLE
Родительский падеж

### ISSUE THREAD

**Issue by rusikf** [petrovich/petrovich-ruby#41]
Были бы хорошо, если бы склонять можно было обычные слова ( не имена )
Например, сейчас не все слова правильно переводятся по родительскому падежу
```ruby
names = ["Овен", "Телец", "Близнецы", "Рак", "Лев", "Дева", "Весы", "Скорпион", "Стрелец", "Козерог", "Водолей", "Рыбы"]
names.map {|name| p.firstname(name, :genitive)}
=> ["Овена",
 "Телеца",
 "Близнецы",
 "Рака",
 "Льва",
 "Девы",
 "Весы",
 "Скорпиона",
 "Стрелеца",
 "Козерога",
 "Водолея",
 "Рыбы"]
```

**Comment by dustalov** [comment]
Добрый день,

эта задача слишком грандиозна для небольшой библиотеки склонения антропонимов. Petrovich работает с ограниченным словником и старается делать это хорошо.

Такая возможность сейчас имеется в библиотеке [Myaso](https://github.com/dustalov/myaso), которая в текущей версии включает привязку к библиотеке mystem через FFI (см. [лицензию](https://legal.yandex.ru/mystem/) на неё). Пример использования есть в [тестах](https://github.com/dustalov/myaso/blob/563ba9d79f611cb503d821c8d04f8f35c351a59a/spec/mystem_spec.rb#L68).

**Comment by rusikf** [comment]
@dustalov , ок, спасибо за ответ!
