### ISSUE TITLE
Родительный падеж для САША (male)

### ISSUE THREAD

**Issue by lenarakhmadeev** [petrovich/petrovich-ruby#42]
```ruby
p = Petrovich.new :male
p.firstname 'саша', :genitive # => 'сашы'
```

при этом 
```ruby
p = Petrovich.new :female
p.firstname 'саша', :genitive # => 'саши'
```
Фикшу в лоб так 

```ruby
#...
res = res.gsub /(ж|ш)ы/, '\1и'
````

**Comment by tanraya** [comment]
Попробуйте ветку https://github.com/petrovich/petrovich-ruby/tree/dev-1.0
Там эта проблема решена (проверил, работает). Скоро будет релиз новой версии, в старой уже не будет изменений. API новой версии меняться уже тоже не будет.

Подключать пока так:

```ruby
gem 'petrovich', github: 'petrovich/petrovich', branch => 'dev-1.0'
```

**Comment by ujifgc** [comment]
Fixed in https://github.com/petrovich/petrovich-rules/commit/263b11141821281514a49450b5d1ab9ff339a43e and 560ebda38ebc4437756ed9623cf1402e7d5836fe
