### ISSUE TITLE
Демо недоступно

### ISSUE THREAD

**Issue by dustalov** [petrovich/petrovich-ruby#43]
Домен `rocketscience.it` потерялся, сайт с демо-версией недоступен. Предлагаю вновь запустить приложение с демонстрацией возможностей библиотеки.

Могу выделить поддомен `petrovich.nlpub.ru` и `petrovich.nlpub.org` (по вкусу), который будет гарантированно продлеваться.

**Comment by tanraya** [comment]
Демо нужно для новой версии выкатывать. Я могу переписать его под новую версию. Но Сначала тебе нужно переписать этот тест - https://github.com/petrovich/petrovich-ruby/blob/master/lib/tasks/evaluate.rake и добавить его в ветку dev-1.0

**Comment by dustalov** [comment]
Ты мог бы создать задачу для этого?

**Comment by tanraya** [comment]
#44

**Comment by dustalov** [comment]
Вновь поднимаю вопрос об адресе демо-версии и вновь предлагаю сделать это на `petrovich.nlpub.ru `.

**Comment by tanraya** [comment]
Поддерживаю. Запили поддомен, то тебе нужно, чтобы поднять его там? Если контейнер, то это с тебя, а переписывание демки для нового Петровича - с меня.

**Comment by dustalov** [comment]
Прекрасно. Давай поступим следующим образом: (1) ты актуализируешь `petrovich-demo`, (2) я готовлю контейнер на его основе, и (3) я запускаю его у себя и предоставляю ссылку.

**Comment by dustalov** [comment]
Вновь поднимаю вопрос.

**Comment by dustalov** [comment]
@tanraya

**Comment by dustalov** [comment]
<http://petrovich.nlpub.ru/>
