### ISSUE TITLE
Petrovich dev-1.0 зависит от непрофильной библиотеки

### ISSUE THREAD

**Issue by ujifgc** [petrovich/petrovich-ruby#45]
Для реализации командной строки в версии 1.0 была введена зависимость от библиотеки для работы с командной строкой `commander`, которая в свою очередь тянет за собой `highline` и неизвестно что потянет в будущем.

Насколько понимаю, Петрович — библиотека для склонения фамилий. Я считаю, зависимости профильных библиотек должны сводиться к минимуму.

Решить это можно переписав командную строку на стандартную библиотеку Ruby `OptionParser` или поручить через `rescue LoadError` установку `commander` пользователю, который недвусмысленно хочет работать с командной строкой и читать в консоли инструкции.

**Comment by tanraya** [comment]
Хм. Предложение интересное. Но я никогда не использовал OptionParser, поэтому, вопрос. Как у него с документацией? Гем commander даёт возможность очень просто документировать команды и опции. Если и OptionParser решает это (сейчас не могу посмотреть), то почему бы и нет?

И было бы неплохо, если пришлете пулл-реквест по этому тикету :)

**Comment by tanraya** [comment]
Кстати, вспомнилось. Мы же хотим в дальнейшем переписать Петровича на Rust, чтобы использовать его через FFI везде, где только можно, чтобы не плодить реализации.

Поэтому, даже если мы сейчас сделаем CLI по-другому, то в итоге-то этот код все равно исчезнет, что грустно.

**Comment by dustalov** [comment]
@tanraya мы ведь уже обсуждали `OptionParser`. Он очень простой, см. https://github.com/dustalov/greeb/blob/master/bin/greeb в качестве примера.

**Comment by dustalov** [comment]
Исправлено в 38623104cd05ba8641e3c4bafae116b71e4c2729.
