### ISSUE TITLE
Ошибка при тестировании dev-1.0 на TravisCI

### ISSUE THREAD

**Issue by tanraya** [petrovich/petrovich-ruby#46]
После коммита @dustalov появилась ошибка на https://travis-ci.org/petrovich/petrovich-ruby
Требуется поправить.

**Comment by dustalov** [comment]
@tanraya эта проблема может быть связана с чем-то другим.

**Comment by ujifgc** [comment]
https://github.com/travis-ci/travis-ci/issues/5239

**Comment by tanraya** [comment]
@ujifgc О, спасибо! Сецчас попробуем :)
