### ISSUE TITLE
Обновление до версии 1.0

### ISSUE THREAD

**Issue by tanraya** [petrovich/petrovich-ruby#48]
Привет!

Эта информация предназначена для @petrovich/porters  - всех, кто делает порты библиотеки на различные языки.

В новой версии библиотеки https://github.com/petrovich/petrovich-ruby появилась функциональность для определения пола.

В файл с правилами были добавлены эвристики для определения пола, новый файл расположен здесь https://github.com/petrovich/petrovich-rules/tree/v1

Также, был переработан API библиотеки, благодаря чему стало проще её использовать, примеры здесь https://github.com/petrovich/petrovich-ruby

И, наконец, был добавлен CLI (command-line interface).

Огромная просьба всем учесь эти изменения в своих портах.
Любые вопросы и предложения можно оставлять в этом обсуждении.

**Comment by mulya** [comment]
Класс, спасибо!

**Comment by dustalov** [comment]
Информация несколько устарела. Обратите внимание, что мы вернулись к структуре «правила в одном файле, эвристике в другом файле»: `rules.{yml,json}` и `gender.{yml,json}`, соответственно.
