### ISSUE TITLE
Проблемы с прохождением тестов

### ISSUE THREAD

**Issue by mikhail-barg** [petrovich/petrovich-ruby#53]
Сравнил результаты прохождения тестов между текущей ruby-версией (https://travis-ci.org/petrovich/petrovich-rules) и своей реализацией на C# (https://github.com/mikhail-barg/petrovich-net-lite).
В ruby на данный момент из 88314 тестов 4986 ошибок. У меня на тех же правилах - из 88572 (surnames.tsv + тесты из других проектов) всего 235 ошибок. 

Меня это очень сильно удивляет, поскольку я портировал логику из ruby вроде бы довольно подробно. 

Как подойти к решению проблемы мне непонятно, поскольку я не знаю с какого конца берутся за руби. Прилагаю логи Трависа для руби, и отчет NUnit для C#.
[log.txt](https://github.com/petrovich/petrovich-ruby/files/367567/log.txt)
[NUnit_TestResult.zip](https://github.com/petrovich/petrovich-ruby/files/367568/NUnit_TestResult.zip)

**Comment by dustalov** [comment]
До изменения базы правил в версии для Ruby всё было точно так же, см. раздел «Оценка аккуратности» в статье <https://habrahabr.ru/post/195874/>.

**Comment by ujifgc** [comment]
@mikhail-barg вы используете для тестов род, указанный в большом проверочном списке?

**Comment by mikhail-barg** [comment]
@ujifgc - да:
```c#
Gender gender = chunks2[0] == "жр" ? Gender.Female : Gender.Male;
```
Собственно в моей-то версии все хорошо. Странно, что плохо в руби-версии 

@dustalov - Довольно странно, ведь у меня используется измененная база правил - ветка `v1`. Плучается, что в руби-версии вместе с переходом на v1 произошла еще и регрессия кода, а при портировании я как-то ее обошел? 
Я могу как-то помочь в решении проблемы?

**Comment by ujifgc** [comment]
Evaluate версии v1 не использует род из списка, только детектор.

Если у вас есть детектор, то отключите использование рода из списка и прогоните тесты.

**Comment by mikhail-barg** [comment]
Спасибо! Стало гораздо понятнее. Я действительно не обратил внимания, что вы не читаете пол из файла. При авто-детекте пола у меня 21 тысяча ошибок ( . Пойду искать проблемы с определением пола.

**Comment by ujifgc** [comment]
На https://github.com/petrovich/petrovich-ruby/pull/56:

#### С автодетектом

на текущем v1:

```
Well, the accuracy on 88314 examples is about 99.5629%.
Sum of the 87928 correct examples and 386 mistakes is 88314.
```

на https://github.com/petrovich/petrovich-rules/pull/24 правил:

```
Well, the accuracy on 88314 examples is about 99.6739%.
Sum of the 88026 correct examples and 288 mistakes is 88314.
```

#### С известным заранее родом:

на v1:

```
Well, the accuracy on 88314 examples is about 99.6875%.
Sum of the 88038 correct examples and 276 mistakes is 88314.
```

на https://github.com/petrovich/petrovich-rules/pull/24:

```
Well, the accuracy on 88314 examples is about 99.8041%.
Sum of the 88141 correct examples and 173 mistakes is 88314.
```

**Comment by mikhail-barg** [comment]
У меня вопрос по прохождению тестов с авто-определением рода. Понятно, что для части фамилий род определяется однозначно ("Иванов"/"Иванова"). Но понятно, что это возможно не всегда. Например по фамилии АБДУЛ-РАХМАН (из файла) понять род нельзя, при этом склонение в зависимости от рода будет разным:

> Сергею АБДУЛ-РАХМАНУ
но
> Наталье АБДУЛ-РАХМАН

То, что в файле для этой фамилии приведены тесты только с мужским полом, мне кажется как-то искажает ситуацию. Не очень понятно, как оценивать корректность работы на таких фамилиях без указания рода.

**Comment by mikhail-barg** [comment]
Кстати, я правильно понимаю, что surnames.tsv построен по данным opencorpora? Думаю попробовать собрать тестовые наборы для имен и отчеств и возможно также автоматизировать собирание фамилий тоже.

**Comment by dustalov** [comment]
Словарь `surnames.tsv` взят по данным морфологического словаря АОТ (<https://nlpub.ru/AOT>).

Кстати, я принял несколько PR от @ujifgc и добавил вызов `rake evaluate` в Travis CI для библиотеки. После обновления базы правил, стало 426 ошибок: <https://travis-ci.org/petrovich/petrovich-ruby/jobs/145395060#L251>.

Меня *очень* беспокоит ситуация с двумя разными базами правил. Надеюсь, @tanraya поможет объединить их.

**Comment by mikhail-barg** [comment]
По АОТ понял, спасибо. С виду сильно совпадает с тем, что можно извлечь из OpenCorposa, но кажется проекты дружественные.

Новые PR видел, в ближайшее время попробую их понять и внедрить у себя. Но меня все еще беспокоит вопрос, про то, как это проходят тесты на склонение фамилий при отсутствии указания рода для неоднозначных случаев. Вероятно я чего-то снова не понимаю, но что будет, если я в surnames.tsv для таких фамилий добавлю примеры склонения в женском роде?

А можно вернуть в джоб трависа вызов 
> $ cat $TRAVIS_BUILD_DIR/../petrovich-ruby/errors.tsv
Мне очень помогала возможность посмотреть реальные примеры с ошибками.

По поводу двух баз, я сравнивал правила веток мастер и v1 до своих коммитов, и в части самих правил там изменения были практически косметическими. Новых коммитов в мастер вроде бы не было. Так что по идее можно смело брать правила из v1, резать и на два файла.

**Comment by dustalov** [comment]
Это два разных репозитория. В репозитории petrovich-ruby (мы сейчас в нём) тестируется последняя версия анализатора на зафиксированной версии правил, см. [.travis.yml](https://github.com/petrovich/petrovich-ruby/blob/8547ed609806b968eb6f7151b69ff177f29a458f/.travis.yml). В репозитории petrovich-rules (правила) тестируется последняя версия анализатора на последней версии правил ветки `v1`, см. [.travis.yml](https://github.com/petrovich/petrovich-rules/blob/2152acd394374319d60ea1f3ec9906c3bd6d981a/.travis.yml). Таким образом, все изменения в правилах покрываются тестами.

Если не ошибаюсь, то где-то обсуждали, что в неоднозначных случаях можно просто брать женский род.

**Comment by mikhail-barg** [comment]
Быть может есть смысл разбить тест на два? Отдельно проверять определение рода, а отдельно - склонение при заданном роде. Задачи все же несколько разные, как мне кажется. 

Так можно будет проверить корректность поведения анализатора на фамилиях, имеющих разные правила склонения в разных родах.

**Comment by dustalov** [comment]
Эти задачи настолько разные, что не имеют между собой почти ничего общего. Я бы вообще убрал это обнаружение. Вместо того, чтобы использовать эвристики, обнаружить род по имени можно при помощи [машинного обучения](http://link.springer.com/chapter/10.1007/978-3-319-12580-0_17), причём модель получается довольно простой.

**Comment by mikhail-barg** [comment]
Тем более есть смысл разбить правила на два файла.

Что касается машинного обучения, мне кажется, текущий набор правил ведет себя весьма и весьма хорошо. Но с другой стороны, надо организовать обучающую выборку, и натравить на нее дерево решений, и я думаю, можно будет набор правил значительно дополнить. Попробую на досуге собрать тесты из данных OpenCorpora.

**Comment by dustalov** [comment]
Упомянутая работа использует логистическую регрессию и я бы не стал заморачиваться: этот метод гораздо проще реализовать. Достаточно будет просто вычислить значение сигмоиды по единовременно обученным параметрам и использовать одинаково во всех реализациях.

**Comment by mikhail-barg** [comment]
Что-то мне сходу не очевидно, как логистическая регрессия может быть применена к этой задаче — факторы-то не числовые. А если делать факторы вида "оканчивается на -ов", "оканчивается на -ова", и т.д., то факторов будет просто вагон. Тут решающие деревья/решающие списки должны давать более компактное и понятное решение. Но надо почитать работу, раз там логистику используют, наверное они что-то знают.

Про OpenCorpora - да, я именно по мотивам pymorphy2 про него вспомнил. Не думаю, что именно "лучше", но дополнить текущий `surnames.tsv` и собрать `firstnames.tsv` и `midnames.tsv` я думаю можно.

**Comment by dustalov** [comment]
В модели используются бинарные признаки, которые легко кодировать и вычислять. Проблем с производительностью нет, см. пример: <http://research.digsolab.com/gender>. Возможно, случайный лес или другой алгоритм на деревьях покажет более аккуратный результат, но это осложняется гораздо большей сложностью реализации. Предлагаю обсудить этот вопрос отдельно вне этой задачи.

@mikhail-barg, @ujifgc: я могу закрыть этот тикет? Насколько понимаю, мы решили проблему с ошибками.

**Comment by mikhail-barg** [comment]
Я бы хотел все-таки понять про тесты с авто-определением пола для неоднозначных фамилий.

**Comment by ujifgc** [comment]
@dustalov думаю, можете

**Comment by mikhail-barg** [comment]
В общем, я набросал парсер для OpenCorpora, собрал два файлика:
* [surnames.oc.tsv](https://github.com/mikhail-barg/petrovich-net-lite/blob/master/src/NPetrovichLite.Tests/Data/surnames.oc.tsv) - данные в формате `surnames.tsv`.
* [surnames.oc.gender.tsv](https://github.com/mikhail-barg/petrovich-net-lite/blob/master/src/NPetrovichLite.Tests/Data/surnames.oc.gender.tsv) - данные вида `<фамилия><пол>` для тестирования определения пола.

На удивление `surnames.oc.tsv` совпадает с исходным `surnames.tsv` практически полностью за исключением:
* добавились строчки для фамилий в женском роде:
было 

> АБАЛЬЯН	АБАЛЬЯН	мр,ед,им
> АБАЛЬЯН	АБАЛЬЯНА	мр,ед,рд
> АБАЛЬЯН	АБАЛЬЯНУ	мр,ед,дт
> АБАЛЬЯН	АБАЛЬЯНА	мр,ед,вн
> АБАЛЬЯН	АБАЛЬЯНОМ	мр,ед,тв
> АБАЛЬЯН	АБАЛЬЯНЕ	мр,ед,пр

стало

> АБАЛЬЯН	АБАЛЬЯН	мр,ед,им
> АБАЛЬЯН	АБАЛЬЯНА	мр,ед,рд
> АБАЛЬЯН	АБАЛЬЯНУ	мр,ед,дт
> АБАЛЬЯН	АБАЛЬЯНА	мр,ед,вн
> АБАЛЬЯН	АБАЛЬЯНОМ	мр,ед,тв
> АБАЛЬЯН	АБАЛЬЯНЕ	мр,ед,пр
> АБАЛЬЯН	АБАЛЬЯН	жр,ед,0

* Еще добавилось около 300 строк с новыми фамилиями

* Удалилась почему-то фамилия "Яшкуль".

Я бы хотел сделать из этого PR на замену текущего `surnames.tsv`. Есть возражения?

Для имен и отчеств файлы сделаю чуть позже.

**Comment by mikhail-barg** [comment]
@ujifgc Игорь, не могли бы вы прокомментировать мое замечание про тесты на фамилии с неопределенным полом?

**Comment by ujifgc** [comment]
@mikhail-barg, если фамилия не подходит под однозначные правила из v1 https://github.com/petrovich/petrovich-rules/blob/74c7f6bf2ddb8e153ec64dcd44bd0746e563742c/rules.yml#L325-L341, то она считается андрогинной и не склоняется. Эти фамилии и вылезают в качестве ошибок склонения мужских фамилий (Бухвальтер): `rake evaluate`. Если андрогинная фамилия у женщины, она и так не склоняется.

В случае прямого указания пола такие фамилии склоняются верно: `USE_GENDER=1 rake evaluate`.

**Comment by mikhail-barg** [comment]
@ujifgc, мне кажется, здесь какая-то проблема. По логу трависа из последнего PR (https://travis-ci.org/petrovich/petrovich-rules/builds/145327566#L76-L77) я вижу, что `rake evaluate` вызывается без `USE_GENDER=1`. 
При этом в списке ошибок нет например фамилии `АБАЛЬЯН`, которая по правилам (на сколько я их понимаю), должна быть андрогинной. По факту она точно андрогинная (см. мой комментарий выше с данными из OpenCorpora).
В текущем `surnames.tsv` для этой фамилии указаны только склонения для мужского рода, и эти строки проходят.
То есть получается, что либо:
* вы для нее определили мужской род и просклоняли соответственно,
* либо определили андрогинный род, но просклоняли как для мужского.

Мне кажется, что ни один из этих вариантов поведения не является корректным. Более того, я считаю, что оба варианта вредны. И тем более вредны, что ruby-реализация является референсной.

Поэтому я и предлагаю разделить тесты на два файла. В одном (для тестирования определения рода) указывать просто пары фамилия-род, например:

>АБАЛЬЯН мр-жр

А во-втором (для определения правильности склонения), использовать указанный для конкретного теста род:

> АБАЛЬЯН АБАЛЬЯН мр,ед,им
> АБАЛЬЯН АБАЛЬЯНА мр,ед,рд
> ...
> АБАЛЬЯН АБАЛЬЯН жр,ед,0

**Comment by ujifgc** [comment]
@mikhail-barg вы правы, если здесь https://github.com/petrovich/petrovich-ruby/blob/b032ac5676f2a1eaf94ff615c9228b7b95b89c8d/lib/petrovich/case/rule.rb#L27-L32 запретить склонение андрогинных фамилий по мужским правилам для неопределённого пола, то добавляется 6707 ошибок склонения андрогинных фамилий для мужчин. Особенность проверочного словаря, судя по всему: куча андрогинных фамилий у мужчин. Видимо, автор кода ориентировался на прохождение теста, а не на одинаковую точность.

**Comment by mikhail-barg** [comment]
> Видимо, автор кода ориентировался на прохождение теста, а не на одинаковую точность.

Вот это-то меня и беспокоит. Получается, мы занимаемся немного самообманом. Я предлагаю внести этот запрет и разделить тесты, как я описал выше.

**Comment by dustalov** [comment]
Давайте разделим.

**Comment by dustalov** [comment]
```
Well, the accuracy on 100980 examples is about 93.2026%.
Sum of the 94116 correct examples and 6864 mistakes is 100980.
```

**Comment by dustalov** [comment]
Для полного счастья осталось только решить проблему с веткой `v1` в репозитории с правилами.

**Comment by ujifgc** [comment]
@dustalov прошу заметить: ветка 0.2.1 (коммит 4bfe6fa657e0830b57a43989dcb430401150022c) совсем не кашляет на правилах v1, поскольку формат первой части не менялся, просто добавились правила детектора в конце:

```
$ git checkout 4bfe6fa657e0830b57a43989dcb430401150022c
$ cd rules/
$ git checkout v1
$ cd ..
$ rake evaluate
I will evaluate the inflector on "petrovich-ruby/spec/data/surnames.tsv" and store errors to "errors.tsv".
        Ac(nominative|male) = 100.0000%
        Ac(genitive|male) = 99.8008%
        Ac(dative|male) = 99.7884%
        Ac(accusative|male) = 99.8008%
        Ac(instrumental|male) = 99.3037%
        Ac(prepositional|male) = 99.7759%
        Ac(nominative|female) = 100.0000%
        Ac(genitive|female) = 99.9401%
        Ac(dative|female) = 99.9401%
        Ac(accusative|female) = 99.9701%
        Ac(instrumental|female) = 99.4636%
        Ac(prepositional|female) = 99.9401%
Well, the accuracy on 88314 examples is about 99.8041%.
Sum of the 88141 correct examples and 173 mistakes is 88314.
```

Я считаю, можно просто заменить мастер-ветку.

**Comment by dustalov** [comment]
Я бы предпочёл выпустить версию 1.1.0, в которой эвристики определения пола отделены от остальных правил и убрана зависимость от Commander (уже готово). Сегодня посмотрю и сделаю.

**Comment by ujifgc** [comment]
Не понял ответ о предпочтениях выпускать 1.1.0. Я говорю о том, что в репозитории petrovich-rules можно master заменить на v1, и все ветки Petrovich должны понять её, поскольку синтаксис важной для них части тот же.

**Comment by mikhail-barg** [comment]
Я думаю, нельзя просто заменить master на v1. В проектах, где используется десериализация в классы (например текущий C#), все отвалится, поскольку в файле будет что-то, не имеющее соответствия в коде.

**Comment by ujifgc** [comment]
Ну, значит, просто добавить в мастер часть с детектором отдельным файлом, а часть инфлектора заменить частью из v1.

**Comment by mikhail-barg** [comment]
Да.

**Comment by dustalov** [comment]
@ujifgc очень круто. Огромное спасибо!
