### ISSUE TITLE
Определение пола

### ISSUE THREAD

**Issue by ujifgc** [petrovich/petrovich-ruby#61]
https://github.com/petrovich/petrovich-eval/pull/4 показывает, что определение пола по имени весьма ненадёжно. Некоторые правила, указанные в детекторе работают с неудовлетворительной точностью.

Предлагаю исключить ненадёжные правила и оставить только те, которые работают на 100%.

Пример: Елена подходит под правило `а$`, как и Никита и множество других мужских имён.

Я считаю, можно внести в правила популярные имена полностью и убрать правила, вносящие жёсткие ошибки (когда род м/ж определился случайно или статистически благоприятно).

**Comment by mikhail-barg** [comment]
Судя по тому, как построено определение пола в итоге по ФИО, отдавать неправильный четкий ответ (М/Ж) куда хуже, чем отказаться от определения и вернуть андрогинный пол, потому что если по одной части ФИО пол андрогинный, то детектор сможет определить пол по другим.

Так что в части удаления ненадежных правил я согласен. Да и со внесением популярных имен - тоже. Покроет бОльшую часть реальных случаев использования.

Со своей стороны попытаюсь в скором времени проработать вопрос автоматического построения правил (см. предложение @dustalov в треде https://github.com/petrovich/petrovich-ruby/issues/53).

Но сначала добавлю данные из OpenCoprora по отчествам. Сейчас немного застрял на парах -ьевич/-иевич.
