### ISSUE TITLE
Неправильно склоняется фамилия Швец

### ISSUE THREAD

**Issue by vadimiztveri** [petrovich/petrovich-ruby#63]
Швец Иван Иванович

род.: Швца Ивана Ивановича
дат.: Швцу Ивану Ивановичу
вин.: Швца Ивана Ивановича
тво.: Швцом Иваном Ивановичем
пре.: Швце Иване Ивановиче

Видимо, надо добавить в исключения.

**Comment by Nakilon** [comment]
Еще на "мертвеце" проверьте.

**Comment by vadimiztveri** [comment]
Мертвец не фамилия. А Щвец довольно распространенная фамилия. Я понимаю, что это исключение, но ведь надо как-то его обрабатывать. 03.04.2018, 11:37, "Victor Maslov" <notifications@github.com>:Еще на "мертвеце" проверьте.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.   -- vadimgalkin.pp.ru

**Comment by dustalov** [comment]
Спасибо за отчёт. Это действительно исключение. Если найдётся время прислать PR в https://github.com/petrovich/petrovich-rules, то я буду рад его принять.

**Comment by installero** [comment]
@dustalov так?

https://github.com/petrovich/petrovich-rules/pull/38

**Comment by dustalov** [comment]
Ответил в комментариях к PR по ссылке.

**Comment by dustalov** [comment]
Закрываю задачу, потому что почти приняли https://github.com/petrovich/petrovich-rules/pull/38, где эта ошибка будет, наконец, исправлена.
