### ISSUE TITLE
Есть ли метод проверяющий в каком склонении слово?

### ISSUE THREAD

**Issue by nemelnikov** [petrovich/petrovich-ruby#64]

**Comment by nemelnikov** [comment]
Интересует проверка слова на именительный падеж, если быть точным.

**Comment by dustalov** [comment]
Добрый день! Такой функциональности в библиотеке нет. Посмотрите в сторону [морфологического анализа](https://nlpub.ru/%D0%9E%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0_%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%B0#.D0.9C.D0.BE.D1.80.D1.84.D0.BE.D0.BB.D0.BE.D0.B3.D0.B8.D1.87.D0.B5.D1.81.D0.BA.D0.B8.D0.B9_.D0.B0.D0.BD.D0.B0.D0.BB.D0.B8.D0.B7). Например, эта задача решается утилитой [Mystem](https://tech.yandex.ru/mystem/).
