### ISSUE TITLE
Не баг, но вопрос

### ISSUE THREAD

**Issue by aitamr** [petrovich/petrovich-ruby#65]
Ребят, ищу какие-нибудь наработки по стандартизации/нормализации имен в кириллице. В своем поиске наткнулся на этот Гит и супер - выглядит как подчти то, что нужно, но не уверен что он. 

Вопрос: ваша библиотека может разобрать и преобразовать текст содержащий имя 
например "Толе Петрову" или "Анатолию Ф. Петрову" (за ранее падеж не известен и имя сокращено)
в объект содержащий 

Standard First Name: Анатолий
Standard Last Name: Петров
Gender: Male?

Закавыка в том, что за ранее не известно что является именем, а что фамилией, присутствует ли отчество или нет, и падеж также не известен.

Если вы видели какие-нибудь библиотеки для русских имен, буду благодарен за наводку(и). Спасибо!

**Comment by dustalov** [comment]
Добрый день!

Увы, данная библиотека не содержит сведений о соответствии между краткими и полными именами. Попробуйте воспользоваться Викисловарём и утилитами для его разбора, такими как [Wikokit](https://github.com/componavt/wikokit) и [JWKTL](https://dkpro.github.io/dkpro-jwktl/).

Пример статьи с нужной разметкой: [https://ru.wiktionary.org/wiki/Колян](https://ru.wiktionary.org/wiki/%D0%9A%D0%BE%D0%BB%D1%8F%D0%BD).
