### ISSUE TITLE
Поддержка имён вида: Петя, Андрюха, Сега, Иринка и т.д.

### ISSUE THREAD

**Issue by tanraya** [petrovich/petrovich-ruby#7]
Нужно написать правила для них. Но, думается мне, сначала нужен инструмент для тестирования, а то есть подозрение, что новые правила могут конфликтовать со старыми и в итоге имена будут склоняться не тем правилом, которым нужно.

Thoughts?

**Comment by selivandex** [comment]
@dustalov добавьте в этот список еще "Санек"

**Comment by dustalov** [comment]
Некоторые из этих имён успешно склоняются правилами. Если что-то работает неправильно, сообщите об этом: <https://github.com/petrovich/petrovich-rules/issues/>.
